services:
    AdrienDupuis\EzPlatformStandardBundle\FieldMapper\ContentFieldMapper\BlockContentTypeIdentifier:
        arguments:
            - '@ezpublish.spi.persistence.content_type_handler'
        tags:
            - { name: ezpublish.search.solr.field_mapper.block }

    AdrienDupuis\EzPlatformStandardBundle\Query\Common\CriterionVisitor\ContentTypeIdentifierIn:
        decorates: ezpublish.search.solr.query.common.criterion_visitor.content_type_identifier_in
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}
