system:
    default:
        content_view:
            link:
                default:
                    template: '@ezdesign/link.html.twig'
                    match: true
    site_group:
        content_view:
            full:
                image:
                    controller: 'AdrienDupuis\EzPlatformStandardBundle\Controller\ImageController::viewAction'
                    match:
                        Identifier\ContentType: ['image']
                plain_text:
                    controller: 'AdrienDupuis\EzPlatformStandardBundle\Controller\PlainTextController::viewAction'
                    match:
                        Identifier\ContentType: ['plain_text']
                web_application:
                    template: '@ezdesign/full/web_application.html.twig'
                    match:
                        Identifier\ContentType: ['web_application']
            embed:
                web_application:
                    controller: 'AdrienDupuis\EzPlatformStandardBundle\Controller\WebApplicationController::viewAction'
                    template: '@ezdesign/embed/web_application.html.twig'
                    match:
                        Identifier\ContentType: ['web_application']
