system:
    default:
        content_view:
            link:
                default:
                    template: '@ezdesign/link.html.twig'
                    match: true
    site_group:
        content_view:
            full:
                plain_text:
                    controller: 'AdrienDupuis\EzPlatformStandardBundle\Controller\PlainTextController::plainTextView'
                    match:
                        Identifier\ContentType: ['plain_text']
